version: '3.3'

services:
  app:
    image: node:22-alpine
    container_name: nextjs-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=0.0.0.0
      - WDS_SOCKET_PORT=3000
    command: sh -c "yarn install --network-timeout 1200000 && yarn dev"

